
// This file has been generated by the GUI designer. Do not modify.
namespace ArduinoCom
{
	public partial class AcAboutDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label labelApplicationName;
		private global::Gtk.Label labelVersion;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelCopyright;
		private global::Gtk.Label labelCompany;
		private global::Gtk.VBox vbox4;
		private global::Gtk.EventBox eventboxURL;
		private global::Gtk.Label labelURL;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewDescription;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ArduinoCom.AcAboutDialog
			this.Name = "ArduinoCom.AcAboutDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ArduinoCom.AcAboutDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelApplicationName = new global::Gtk.Label ();
			this.labelApplicationName.Name = "labelApplicationName";
			this.labelApplicationName.LabelProp = global::Mono.Unix.Catalog.GetString ("Arduino Com");
			this.vbox2.Add (this.labelApplicationName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelApplicationName]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelVersion = new global::Gtk.Label ();
			this.labelVersion.Name = "labelVersion";
			this.labelVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("Version 0.0.0.0");
			this.vbox2.Add (this.labelVersion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelVersion]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelCopyright = new global::Gtk.Label ();
			this.labelCopyright.Name = "labelCopyright";
			this.labelCopyright.LabelProp = global::Mono.Unix.Catalog.GetString ("Copyright © 2013");
			this.vbox3.Add (this.labelCopyright);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelCopyright]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelCompany = new global::Gtk.Label ();
			this.labelCompany.Name = "labelCompany";
			this.labelCompany.LabelProp = global::Mono.Unix.Catalog.GetString ("Toxic Bakery");
			this.vbox3.Add (this.labelCompany);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelCompany]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.eventboxURL = new global::Gtk.EventBox ();
			this.eventboxURL.CanFocus = true;
			this.eventboxURL.Events = ((global::Gdk.EventMask)(4194302));
			this.eventboxURL.Name = "eventboxURL";
			this.eventboxURL.AboveChild = true;
			// Container child eventboxURL.Gtk.Container+ContainerChild
			this.labelURL = new global::Gtk.Label ();
			this.labelURL.Name = "labelURL";
			this.labelURL.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"#0000FF\"><u>http://toxicbakery.com/</u></span>");
			this.labelURL.UseMarkup = true;
			this.labelURL.Selectable = true;
			this.eventboxURL.Add (this.labelURL);
			this.vbox4.Add (this.eventboxURL);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.eventboxURL]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewDescription = new global::Gtk.TextView ();
			this.textviewDescription.Buffer.Text = "Serial console designed for Arduino and other COM port based hardware. Designed b" +
				"y Ian Thomas and Toxic Bakery.";
			this.textviewDescription.Sensitive = false;
			this.textviewDescription.CanFocus = true;
			this.textviewDescription.Name = "textviewDescription";
			this.textviewDescription.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textviewDescription);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w10.Position = 3;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w11.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w12.Position = 0;
			// Internal child ArduinoCom.AcAboutDialog.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 10;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonOk]));
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 425;
			this.Show ();
		}
	}
}
